name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git .
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install 18
          nvm use 18
      - name: Build
        run: |
          npm ci
          npx expo export:web
      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv web-build/* .
          rm -rf web-build
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
