name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
      - name: Setup Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Setup Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx expo export:web
      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r web-build/* .
          rm -rf web-build
          touch .nojekyll
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
