name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Setup Node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx expo export:web
      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv web-build/* .
          rm -rf web-build
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
