name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Setup Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sudo npm install -g n
          sudo n 18
          hash -r
      - name: Build
        run: |
          npm ci
          npx expo export:web
      - name: Deploy
        run: |
          cd web-build
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -M gh-pages
          git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
