name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Setup Node
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3.4.1
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx expo export:web
      - name: Setup Pages
        uses: actions/configure-pages@f156874f8191504dae5b037c6438fe28729530e4 # v3.0.6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356d4f9e1461e48dc # v2.0.0
        with:
          path: 'web-build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@0243b6c10d06cb8e95ed8ee471231877621202c0 # v2.0.4
